export const loginConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAIL: "LOGOUT_FAIL"
}


export const categoryConstants = {
    GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
    GET_CATEGORY_FAIL: "GET_CATEGORY_FAIL",

    CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
    CREATE_CATEGORY_FAIL: "CREATE_CATEGORY_FAIL",

    DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
    DELETE_CATEGORY_FAIL: "DELETE_CATEGORY_FAIL",

    UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
    UPDATE_CATEGORY_FAIL: "UPDATE_CATEGORY_FAIL"
}


export const productConstants = {
    GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
    GET_ALL_PRODUCT_FAIL: "GET_ALL_PRODUCT_FAIL",

    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAIL: "ADD_PRODUCT_FAIL",

    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",

    EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
    EDIT_PRODUCT_FAIL: "EDIT_PRODUCT_FAIL"
}


export const bannerConstant = {
    ADD_BANNER_SUCCESS: "ADD_BANNER_SUCCESS",
    ADD_BANNER_FAIL: "ADD_BANNER_FAIL",

    GET_BANNER_SUCCESS: "GET_BANNER_SUCCESS",
    GET_BANNER_FAIL: "GET_BANNER_FAIL",

    DELETE_BANNER_SUCCESS: "DELETE_BANNER_SUCCESS",
    DELETE_BANNER_FAIL: "DELETE_BANNER_FAIL",

    UPDATE_BANNER_SUCCESS: "UPDATE_BANNER_SUCCESS",
    UPDATE_BANNER_FAIL: "UPDATE_BANNER_FAIL"
}


export const messageConstants = {
    REMOVE_CATEGORY_MESSAGE_AND_ERROR: "REMOVE_CATEGORY_MESSAGE_AND_ERROR",
    REMOVE_PRODUCT_MESSAGE_AND_ERROR: "REMOVE_PRODUCT_MESSAGE_AND_ERROR",
    REMOVE_BANNER_MESSAGE_AND_ERROR: "REMOVE_BANNER_MESSAGE_AND_ERROR",
    REMOVE_LOGIN_MESSAGE_AND_ERROR: "REMOVE_LOGIN_MESSAGE_AND_ERROR"
}